spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/datajpa
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
#        show_sql: true  // JPA? ??? sql? ??? ???? ??

logging.level:
  org.hibernate.SQL: debug # JPA? ??? sql? ?? ??? ???? ??

